# (PART) Básico {-}

# Introdução

## Conceitos Principais

**Grupos independentes**  

**Grupos pareados**  

**Tipo paramétrico**  

**Tipo não paramétrico**


## Testes de Hipótese

### Hipósete nula e alternativa

### O significado de p-valor

## Testes de Comparação Amostral

São diversos os modelos de dados que são analisados, e cada um destes tem suas características probabilisticas; quando queremos comparar grupos amostrais de nossos dados, são necessários testes para entender melhor como essa amostra se comporta.  

Na Tabela abaixo são apresentados alguns dos principais testes de **Comparação entre Amostras**, cada um dos termos da tabela, assim como os métodos, serão explicados ao longo deste livro/resumo.

Table: (\#tab:CompAm) Testes Para Comparação de Amostras

|          **Quantidade**         |      **Tipo**      |            **Método de Teste**           |
|:-------------------------------:|:------------------:|:----------------------------------------:|
|    **2 grupos independentes**   |   _paramétricos_   | Int. e lim. de confiança (1 ou 2 grupos) |
|                                 |                    | t de Student (1 ou 2 grupos)             |
|                                 |                    | Comparação entre 2 proporções            |
|                                 | _não paramétricos_ | Qui-quadrado $\chi^2$                    |
|                                 |                    | U de Mann Whitney                        |
|                                 |                    | Prova de Fischer                         |
|      **2 grupos pareados**      |    _paramétrico_   | t de Student pareado                     |
|                                 | _não paramétricos_ | Prova de MacNemar                        |
|                                 |                    | Prova de Wilcoxon                        |
| $\geq$ **3 grupos independentes** |    _paramétrico_   | ANOVA de 1 ou 2 vias                     |
|                                 | _não paramétricos_ | Qui-quadrado $\chi^2$                    |
|                                 |                    | Kruskall Wallis                          |
| $\geq$ **3 grupos pareados**      |    _paramétrico_   | ANOVA p/ medidas repetidas               |
|                                 |  _não paramétrico_ | Teste de Friedman                        |


Na linha 1 da tabela \@ref(tab:CompAm) as abreviações **Int** e **lim** significam **intervalo** e **limite**, respectivamente.




