# Estatística
Em probabilidade e estatística, existem diversos conceitos e axiomas que são fundamentais para o entendimento e a resolução dos problemas. Neste capítulo serão desenvolvidos os pontos que serão mais aplicados ao decorrer do livro, demais conceitos que sejam considerados extras, serão apenas indicados e referências para estes são deixadas a disposição.



## Conceitos Básicos de Estatística
Entre os conceitos mais básicos da estatística, estão a **média, moda** e **mediana**, de forma direta a explicação de cada uma é dada na sequência

**Média -** Valor médio\
**Mediana -** O valor central\
**Moda -** O valor que mais se repete

### Média
A **média** como citado anteriormente, é o valor médio de uma sequência de dados, matematicamente isso significa a soma de todos os termos, divido pela quantidade dos termos, como apresentado na equação \@ref(eq:media)

\begin{equation}
  \bar{x} = \frac{1}{n} \sum_{i=1}^n x_i
  (\#eq:media)
\end{equation}

Para fixar melhor este conceito, vejamos o exemplo abaixo.

---------------------------  

::: {.example} 
Dado o seguinte registro da velocidade de 13 carros: 

>vel = [99,86,87,88,111,86,103,87,94,78,77,85,86]  

calcular a média desses dados.

**Resolução:** Para calcular a média, basta sormamos todos os termos e dividirmos pela quantidade de termos, isto é
$$
\bar{x} = \frac{1}{13}(99+86+87+111+86+103+87+94+78+77+85+86) = 89.77
$$
Portanto, a média das velocidades coletadas é \(\bar{x} = 89.77\)
:::  

---------------------------  

Outro conceito que usualmente aparece, é o de **média ponderada**, neste caso é associado um determinado ''peso'' a cada um dos termos da amostra.


### Mediana

### Moda

### Variância
A **Variância** é um parâmetro que compara o quão distantes estão os valores de determinado grupo de dados com relação a média deste mesmo grupo. A mesma pode ser do tipo **Amostral** ou **Populacional** e a diferença fica mais explicita na equação que as definem.

**Variância Amostral**
\begin{equation}
s^2 =  \frac{1}{n-1}\sum_{i=1}^n(x_i - \bar{x})^2 = \frac{1}{n-1}\left[\sum x_i^2 - n \bar{x}^2 \right]
\end{equation}

**Variância Populacional**
\begin{equation}
\sigma^2 = \sum_{i=1}^N \frac{(x_i - \bar{\mu})^2}{N} = \frac{\sum x_i^2}{N} - \bar{\mu}^2  
\end{equation}

#### Demonstração das relações de Variância  

Seja a **variância amostral** dada pela relação inicial:
  $$
  s^2 = \frac{\sum_{i=1}^n (x_i - \bar{x})^2}{n-1}
  $$
vamos mostrar que a mesma pode ser escrita como sendo
  $$
  s^2 = \frac{1}{n-1} \left[\sum x_i^2 - n\bar{x}^2 \right]
  $$


::: {.proof}
  \begin{align*}
  s^2 & = \frac{\sum_{i=1}^n (x_i - \bar{x})^2}{n-1} \\
      & = \frac{\sum_{i=1}^n (x_i^2 -2x_i \bar{x} + \bar{x}^2)}{n-1} \\
      & = \frac{1}{n-1} \left(\sum x_i^2 - 2\sum x_i\bar{x} + \sum\bar{x}^2   \right) \\
      & = \frac{1}{n-1} \left[\sum x_i^2 - 2\sum x_i \left(\frac{1}{n} \sum x_i \right) + \sum \left(\frac{1}{n} \sum x_i \right)^2   \right] \\
      & = \frac{1}{n-1} \left[\sum x_i^2 - \frac{2}{n}\left(\sum x_i \right)^2 + n\left(\frac{1}{n}\right)^2 \left( \sum x_i \right)^2   \right]\\
      & = \frac{1}{n-1} \left[\sum x_i^2 - \frac{2n}{n^2}\left(\sum x_i \right)^2 + n\left(\frac{1}{n}\right)^2 \left( \sum x_i \right)^2   \right]\\
      & = \frac{1}{n-1} \left[\sum x_i^2 + \frac{1}{n^2}(n-2n)  \left( \sum x_i \right)^2   \right]\\
      & = \frac{1}{n-1} \left[\sum x_i^2 + \left(\frac{1}{n} \sum x_i \right)^2 (-n)  \right]\\
      & = \frac{1}{n-1} \left[\sum x_i^2 - n\bar{x}^2 \right]
  \end{align*}
:::  

Para a **Variância Populacional** segue do resultado anterior

::: {.proof}
\begin{align*}
\sigma^2 &= \frac{\sum_{i=1}^N (x_i - \bar{\mu})^2}{N} \\
         &= \frac{1}{N} \left[\sum x_i^2 - N \bar{\mu}^2 \right] \\
         &= \frac{\sum x_i^2}{N} - \bar{\mu}^2
\end{align*}
:::  

Segue agora alguns exemplos da aplicação da variância.  

Os mesmos foram retirados da referência...

### Desvio Padrão







